### ISSUE TITLE
[Enhancement] When there's too many classes in class restrictions

### ISSUE THREAD

**Issue by goflishMC** [promcteam/prorpgitems#134]
When there's too many classes in class restrictions it stretches the text out like this: https://i.imgur.com/9B1LzOz.png

In engine.yml under the class section add a new option called, "max-class-per-line"

```
            class:
            enabled: true
            # This would only allow 3 classes per line
            # If there's more than 3 classes it would start a new line
            max-classes-per-line: 3
            name: 'Class'
            format:
              main: '&c%state%%name%: %value%'
              value:
                separator: '&7/'
                color: '&f'
```
