### ISSUE TITLE
[Enhancement] unidentified items

### ISSUE THREAD

**Issue by goflishMC** [promcteam/prorpgitems#141]
Add the ability to set the material type for unidentified items.

In the identify module, in the items folder add new option for material Id and custom model data.

Example:
material: PAPER
model-data: 9

Currently, the unidentified item shows you what the item is going to be, you just can't see the stats until it's identified.

Adding this new feature would allow unidentified items to have the type of item hidden also.

**Comment by lordsrubka5** [comment]
yeah I suggested this a while in the pinned messages of general chat.

Preferably if we can group couple item generators and/or tiers to different items would be great
Basically so that we can make one custom model texture for example common items and one for rare
or to group couple items as "Random Nature Armor Box" that would give a random item from the listed
itemgen names as well as them having individual chances

```
CommonBox:
  material: PAPER
  model-data: 1
  name: 'Common Unidentified Item'
  lore:
  - '%item_rarity_placeholder%'
  - '%item_level_placeholder%'
  - '%item_required_level_placeholder%'
  - ''
  - 'Hold in hand and right click to open'
  #Rarity of the the box
  rarity: Common
  #Level of the box
  level: 10
  #Required level to open it
  required-level: 5
  #Adds a whitelist of rarities, for all rarities add []
  rarity-list:
  - Common
  #Item generator item names aka ids, for all items add []
  items:
  - SomeCommonHelmet
  - SomeCommonSword
  #Should the whitelist be turned to blacklist
  item-blacklist: false
  #Should there be a message in chat when they open the box
  notify-chat: true
  #Lists of items that trigger the message, for all items add []
  notify-list:
  - SomeCommonSword
  #Should the whitelist of message items turn to blacklist
  blacklist-message: false
  #Edit the actual message format
  message: '%player% has opened %box_name% and identified %item_name_from_itemgen_file_first_row%!'
```
I think thats all? Might have forgot something will see later
