### ISSUE TITLE
[Enhancement] Stat/damage/defense generator alternative roll method

### ISSUE THREAD

**Issue by gMithos** [promcteam/prorpgitems#155]
Currently, you can give a min and max for a desired range, but it also returns a range of damage/defense that will be applied per hit.
It would be really nice to be able to specify a range and then it would only roll 1 number onto the item from the given range.

**Comment by goflishMC** [comment]
```
      physical:
        chance: 0.0
        scale-by-level: 1.0
        min: 1.0
        max: 30.0
        flat-range: true
        # If true the damage would be a single number instead of a range
        # The single number that gets rolled would be between 1 and 30 using the above
        # Would look something like "Physical Damage: 18", since 18 is between 1 and 30
        single-damage: true
```
