### ISSUE TITLE
[Enhancement] Percentage Chance

### ISSUE THREAD

**Issue by goflishMC** [promcteam/prorpgitems#2]
When you create an item with the item generator you can set the chance for stats to appear on the item.

Stats could be anything from damage, defense, item stats like dodge chance etc.

Here's an example of how chance is setup

```
    damage-types:  
    minimum: 1  
    maximum: 3  
    lore-format:  
    - '%DAMAGE_PHYSICAL%'  
    - '%DAMAGE_MAGICAL%'  
    - '%DAMAGE_POISON%'  
    - '%DAMAGE_FIRE%'  
    - '%DAMAGE_WATER%'  
    - '%DAMAGE_WIND%'  
    - ''  
    - '%DAMAGE__VANILLA_GENERIC%'  
    list:  
      physical:  
        chance: 100.0  
        scale-by-level: 1.025  
        min: 0.0  
        max: 1.0  
      _vanilla_generic:  
        chance: 0.0  
        scale-by-level: 1.0  
        min: '0'  
        max: '0'  
      magical:  
        chance: 10.0  
        scale-by-level: 1.0  
        min: 0.0  
        max: 0.1
```

If you give yourself this item it will give you items like this: https://i.imgur.com/zMnFJKq.png

In that example image you can see that it gave only water damage, which is basically working the way this was coded. (it could roll with 1-3 damage types and it rolled with 1)

The issue is that even if you have 100% chance on 1 item stat and other item stats have less than 100%, then item stat with 100% doesn't always show up on the item.

- damage-types
- defense-types
- item-stats
- sockets
- essence
- rune
- abilities
