### ISSUE TITLE
[Enhancement] Vanilla Attributes

### ISSUE THREAD

**Issue by xMystik** [promcteam/prorpgitems#208]
**Is your feature request related to a problem? Please describe.**
Currently the Vanilla Attributes have no way of being changes on an item generator file besides the base attack speed.

**Describe the solution you'd like**
A new section inside the generator file looking like this.
```
vanilla-attributes:
    minimum: 0
    maximum: 2
    list:
      ATTACK_SPEED:
        chance: 100.0
        amount: 2.0
```
