### ISSUE TITLE
[Bug]: Issue with tier-id in drops module

### ISSUE THREAD

**Issue by materialplane** [promcteam/prorpgitems#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```yaml
items:
  custom_items:
    chance: 100.0
    module-id: 'item_generator'
    item-id: 'random'
    tier-id: 'common'
```

When setting `module-id` to `item_generator` and `item-id` to `random` and `tier-id` to `common` I get this error when I give myself the drop: https://paste.travja.dev/amepasucoq.properties

When setting `module-id` to `custom_items` and `item-id` to `random` and `tier-id` to `common` it just tells me min chat when I give myself the drop that 0 items were given.

 

### Expected Behavior

I should get random common items from the module specified based on the common tier.

### Steps To Reproduce

setup your drop file to give common items from the custom items module and the item generator module (test them separately) and try to give them to your self using /drops command.

### Environment

```markdown
- Server Software: 1.21.1 Paper Spigot
- Divinity Version: 1.0.2-R0.1
- Codex Version: 1.0.1-R0.8
- Plugins: https://i.imgur.com/Riji3NX.png
```

### latest.log

https://paste.travja.dev/ameneluduc.sql
