### ISSUE TITLE
[Enhancement] import ability from mythicmob

### ISSUE THREAD

**Issue by YKDZ** [promcteam/prorpgitems#29]
**Describe the solution you'd like**
I hope to import mythicmob skill to make items such as staff.
like this
```
  abilities:
    minimum: 0
    maximum: 0
   ......
    list:
      ability-1:
        chance: 0.0
        cooldown: 5.0
        lore-format:
        - '&bSample Ability: &7[&f%key%&7]'
        mythicmob-id: fireball
        trigger-click: Right
```
My English is not good. I hope you can understand me.
